name: Secure Pipeline

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  secure-pipeline:
    name: Secure Pipeline Checks
    runs-on: ubuntu-latest

    steps:
    # Checkout de code
    - name: Checkout code
      uses: actions/checkout@v3

    # SAST (Static Application Security Testing) met CodeQL
    - name: Run CodeQL analysis
      uses: github/codeql-action/analyze@v2
      with:
        languages: python

    # Controleer dependencies op kwetsbaarheden
    - name: Dependency Check
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: fs
        vulnerability-type: library
        exit-code: "1"

    # Zoek naar geheimen in de code
    - name: Secret Scanning
      uses: actions/checkout@v3

    - name: Scan for secrets
      uses: step-security/secret-scanner-action@v1
