name: Secure Pipeline

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  secure-pipeline:
    name: Secure Pipeline Checks
    runs-on: ubuntu-latest

    steps:
    # Checkout de code
    - name: Checkout code
      uses: actions/checkout@v3

      # 2. CodeQL Initialiseren
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: python

      # 3. CodeQL Analyse
    - name: Run CodeQL Analysis
      uses: github/codeql-action/analyze@v2

    # Controleer dependencies op kwetsbaarheden
    - name: Dependency Check
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: fs
        vulnerability-type: library
        exit-code: "1"

    # Zoek naar geheimen in de code
    - name: Secret Scanning
      uses: actions/checkout@v3

    - name: Secret Scanning
      uses: trufflesecurity/trufflehog@v3.67.1
      with:
        path: .  # Scant de volledige repository
        base: HEAD~1
        head: HEAD
