name: Secure Pipeline Checks

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
  schedule:
    - cron: '0 14 * * 6'  # Elke zaterdag om 14:00 UTC

jobs:
  analyze:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    permissions:
      security-events: write

    steps:
      # Beveilig de runner
      - name: Harden the runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      # Haal de repository op
      - name: Checkout repository
        uses: actions/checkout@v4

      # Initialiseer CodeQL
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: python

      # Autobuild voor compatibiliteit
      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      # Voer CodeQL analyse uit
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

      # Controleer dependencies op kwetsbaarheden met Trivy
      - name: Dependency Check
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          exit-code: "1"

      # Zoek naar geheimen in de code met TruffleHog
      - name: Secret Scanning
        uses: trufflesecurity/trufflehog@v3.67.1
        with:
          path: .  # Scant de volledige repository
