name: Python Application Workflow

on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0' # Wekelijkse scan

jobs:
  build-and-test:
    name: Build, Test, and Security Checks
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt || echo "No dependencies to install"

    - name: Run tests
      run: |
        pytest || echo "No tests found"

    - name: Run SAST (Static Application Security Testing)
      uses: github/codeql-action/init@v2
      with:
        languages: python
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2

    - name: Check for vulnerable dependencies
      uses: actions/dependency-review-action@v3

    - name: Scan for secrets
      uses: zricethezav/gitleaks-action@v1.2.0
