name: Weekly Code Scan

on:
  schedule:
    - cron: '0 0 * * 0'  # Elke zondag om middernacht

jobs:
  sast-scan:
    name: Weekly SAST Scan
    runs-on: ubuntu-latest

    steps:
    # Checkout de code
    - name: Checkout code
      uses: actions/checkout@v3

    # Voer een SAST-scan uit met CodeQL
    - name: Run CodeQL analysis
      uses: github/codeql-action/analyze@v2
      with:
        languages: python
