name: Weekly Code Scan

on:
  schedule:
    - cron: '0 0 * * 0'  # Elke zondag om middernacht

jobs:
  sast-scan:
    name: Weekly SAST Scan
    runs-on: ubuntu-latest

    steps:
      # 1. Code ophalen
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. CodeQL Initialiseren
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: python

      # 3. CodeQL Analyse
      - name: Run CodeQL Analysis
        uses: github/codeql-action/analyze@v2
